from __future__ import annotations

from shared.constants.status import (
    INVENTORY_STATUS_AVAILABLE,
    INVENTORY_STATUS_OUT_OF_STOCK,
    INVENTORY_STATUS_RESERVED,
    ORDER_STATUS_CANCELLED,
    ORDER_STATUS_CONFIRMED,
    ORDER_STATUS_CREATED,
    ORDER_STATUS_DELIVERED,
    ORDER_STATUS_SHIPPED,
    PAYMENT_STATUS_COMPLETED,
    PAYMENT_STATUS_FAILED,
    PAYMENT_STATUS_PENDING,
)
from shared.constants.topics import ALL_TOPICS

__all__ = [
    "ALL_TOPICS",
    "INVENTORY_STATUS_AVAILABLE",
    "INVENTORY_STATUS_OUT_OF_STOCK",
    "INVENTORY_STATUS_RESERVED",
    "ORDER_STATUS_CANCELLED",
    "ORDER_STATUS_CONFIRMED",
    "ORDER_STATUS_CREATED",
    "ORDER_STATUS_DELIVERED",
    "ORDER_STATUS_SHIPPED",
    "PAYMENT_STATUS_COMPLETED",
    "PAYMENT_STATUS_FAILED",
    "PAYMENT_STATUS_PENDING",
]
