apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bfsi-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/bfsi-agentic-ai-platform.git
    targetRevision: main
    path: ci-cd/argo-cd/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: bfsi-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
